NDPH-ARTS/mts-services

- trial-config-service/pom.xml
- trial-config-service/src/main/java/uk/ac/ox/ndph/mts/trial_config_service/config/GitRepo.java
- trial-config-service/src/main/java/uk/ac/ox/ndph/mts/trial_config_service/controller/TrialConfigController.java
- trial-config-service/src/main/resources/application.properties
- trial-config-service/src/test/java/uk/ac/ox/ndph/mts/trial_config_service/config/GitRepoTest.java
- trial-config-service/src/test/java/uk/ac/ox/ndph/mts/trial_config_service/service/TrialConfigServiceTest.java
fixed code smells and copied 291 changes
> Arts 291 code smells

- .github/workflows/code-analysis.yml
- .github/workflows/docker-build-push.yml
- pom.xml
* Add Jacoco to provide code coverage reports locally and in SonarCloud
* Will also allow to start our _Actions_ once this PR is merged to main
> [ARTS-300] Add coverage reports

- trial-config-service/src/test/java/uk/ac/ox/ndph/mts/trial_config_service/service/TrialConfigServiceTest.java
Noticed code smells from latest changes to feature branch - corrected the test issues
> cleaning code smell issues

- site-service/src/main/java/uk/ac/ox/ndph/mts/site_service/repository/AzureFhirRepository.java
- site-service/src/main/java/uk/ac/ox/ndph/mts/site_service/repository/FhirRepository.java
- site-service/src/main/java/uk/ac/ox/ndph/mts/site_service/service/SiteService.java
- site-service/src/test/java/uk/ac/ox/ndph/mts/site_service/service/SiteServiceTests.java
Added the Research study to an Org
> Added ResearchStudy

- trial-config-service/src/main/java/uk/ac/ox/ndph/mts/trial_config_service/config/WebConfig.java
- trial-config-service/src/main/java/uk/ac/ox/ndph/mts/trial_config_service/controller/TrialConfigController.java
- trial-config-service/src/main/java/uk/ac/ox/ndph/mts/trial_config_service/model/Role.java
- trial-config-service/src/main/java/uk/ac/ox/ndph/mts/trial_config_service/model/Trial.java
- trial-config-service/src/main/java/uk/ac/ox/ndph/mts/trial_config_service/model/TrialSite.java
- trial-config-service/src/test/java/uk/ac/ox/ndph/mts/trial_config_service/config/GitRepoTest.java
- trial-config-service/src/test/java/uk/ac/ox/ndph/mts/trial_config_service/controller/TrialConfigControllerTest.java
- trial-config-service/src/test/java/uk/ac/ox/ndph/mts/trial_config_service/service/TrialConfigServiceTest.java
improving code coverage to allow successful build
> ensuring code coverage is met

- trial-config-service/src/main/java/uk/ac/ox/ndph/mts/trial_config_service/config/WebConfig.java
- trial-config-service/src/main/java/uk/ac/ox/ndph/mts/trial_config_service/controller/TrialConfigController.java
- trial-config-service/src/main/java/uk/ac/ox/ndph/mts/trial_config_service/model/Role.java
- trial-config-service/src/main/java/uk/ac/ox/ndph/mts/trial_config_service/model/Trial.java
- trial-config-service/src/main/java/uk/ac/ox/ndph/mts/trial_config_service/model/TrialSite.java
- trial-config-service/src/test/java/uk/ac/ox/ndph/mts/trial_config_service/config/GitRepoTest.java
- trial-config-service/src/test/java/uk/ac/ox/ndph/mts/trial_config_service/config/WebConfigTest.java
- trial-config-service/src/test/java/uk/ac/ox/ndph/mts/trial_config_service/controller/TrialConfigControllerTest.java
- trial-config-service/src/test/java/uk/ac/ox/ndph/mts/trial_config_service/service/TrialConfigServiceTest.java
> Code coverage

- .gitignore
- api-tests/config/conf.js
- api-tests/data/practitioner-service/createperson.js
- api-tests/package-lock.json
- api-tests/package.json
- api-tests/specs/practitioner-service/createperson.js
The PR covers the api automation tests written on mocha chai api framework written using javascript. Mochawesome reports are generated from the automation test run.
The ticket, https://ndph-arts.atlassian.net/browse/ARTS-293 is a test approach that lists out the wide variety of tests / scenarios considered to check the practitioner service end point responses.
**Note:** @balteravishay @mdp0 @tamirkamara I had to close the previous pull request due to unresolvable merge conflicts. I have refactored the code as per the provided feedback. attaching sceenshots for reference. Please re-approve my pr, sorry for the inconvenience.
> [ARTS-184] Practitioner Service automation api tests

- api-tests/package-lock.json
- api-tests/package.json
The PR is related to dependency vulnerability, the following have been upgraded,
1. qs
2. mem
3. extend
4. superagent
> [ARTS-371] - Resolve security vulnerability from dependencies

- api-tests/README.md
- api-tests/data/common/headers.js
- api-tests/data/role-service/roleservice.js
- api-tests/specs/role-service/roleservice.js
The PR includes automation api tests written around role service and trial config service end points. 
Jira under test is https://ndph-arts.atlassian.net/browse/ARTS-98.
> [ARTS-98] Role Service API Automation Tests

- .github/workflows/docker-build-push.yml
- practitioner-service/src/main/java/uk/ac/ox/ndph/mts/practitioner_service/package-info.java
> Named images - PR1

- practitioner-service/pom.xml
- practitioner-service/src/main/java/uk/ac/ox/ndph/mts/practitioner_service/model/Practitioner.java
- practitioner-service/src/main/java/uk/ac/ox/ndph/mts/practitioner_service/model/PractitionerAttributeConfiguration.java
- practitioner-service/src/main/java/uk/ac/ox/ndph/mts/practitioner_service/model/PractitionerConfiguration.java
- practitioner-service/src/main/java/uk/ac/ox/ndph/mts/practitioner_service/model/Response.java
- practitioner-service/src/main/java/uk/ac/ox/ndph/mts/practitioner_service/model/ValidationResponse.java
- practitioner-service/src/main/java/uk/ac/ox/ndph/mts/practitioner_service/validation/PractitionerValidation.java
ARTS-374 Remove Lombok dependency from practitioner-service
I got my commit messages wrong for this fix, stating ARTS-375 instead of ARTS-374. Hope this isn't a problem for the git history.
> [ARTS-374] Remove Lombok dependency from practitioner-service

- api-tests/specs/practitioner-service/createperson.js
- api-tests/specs/role-service/permissions.js
- api-tests/specs/role-service/roleservice.js
Fixed the failing api tests
- updated endpoint uri 
- and deleted before each as suggested by @mdp0  for permissions and practitioner services api spec files
> Fix failing api tests

- build-tools/src/main/java/uk/ac/ox/ndph/mts/json_schema_generator/model/ConfigServer.java
- build-tools/src/main/java/uk/ac/ox/ndph/mts/json_schema_generator/model/SpringCloud.java
- build-tools/src/main/java/uk/ac/ox/ndph/mts/json_schema_generator/model/TrialConfigFile.java
Keeping the json schema up-to-date, had to update the models in the tool in order to match the recent definiton.json with the changes of the new config server, role service and site service. Also there is a [matching PR ](https://github.com/NDPH-ARTS/mts-trial-deployment-config/pull/37#) in the mts-deployment repo.
- [ARTS-593] - update json schema objects
> [ARTS-593][FIX]Update the build-tools models with the most recent definition.json

- practitioner-service/README.md
Updated readme of the practitioner-service with role assignment functionality.
- [ARTS-467]
[ARTS-467]: https://ndph-arts.atlassian.net/browse/ARTS-467
> [ARTS-467] Update readme with role-assignment

- .github/workflows/docker-build-push.yml
- config-server/Dockerfile
- discovery-server/Dockerfile
- discovery-server/README.md
- discovery-server/pom.xml
- discovery-server/src/main/java/uk/ac/ox/ndph/mts/discoveryserver/DiscoveryServerApplication.java
- discovery-server/src/main/resources/application.yml
- init-service/Dockerfile
- pom.xml
- practitioner-service/Dockerfile
- role-service/Dockerfile
- sample-service/Dockerfile
- site-service/Dockerfile
Adding discovery server service, with no wiring except of adding the service to CI
- [ARTS-352] - Adding discovery server 
[ARTS-352]: https://ndph-arts.atlassian.net/browse/ARTS-352
> [ARTS-352] Add Discovery Server service

- config-server/Dockerfile
- config-server/pom.xml
- config-server/src/main/java/uk/ac/ox/ndph/mts/configserver/package-info.java
- discovery-server/Dockerfile
- discovery-server/pom.xml
- discovery-server/src/main/java/uk/ac/ox/ndph/mts/discoveryserver/DiscoveryServerApplication.java
- discovery-server/src/main/java/uk/ac/ox/ndph/mts/discoveryserver/package-info.java
- init-service/Dockerfile
- init-service/pom.xml
- init-service/src/test/java/uk/ac/ox/ndph/mts/init_service/service/PractitionerServiceTest.java
- init-service/src/test/java/uk/ac/ox/ndph/mts/init_service/service/RoleServiceTest.java
- init-service/src/test/java/uk/ac/ox/ndph/mts/init_service/service/SiteServiceTest.java
- pom.springcloud.xml
- pom.web.xml
- pom.xml
- practitioner-service/Dockerfile
- practitioner-service/pom.xml
- role-service/Dockerfile
- role-service/pom.xml
- sample-service/Dockerfile
- sample-service/pom.xml
- site-service/Dockerfile
- site-service/pom.xml
Include 3 types of POMs:
1. The root parent with all module references, spring-boot dependency and other things we want to inherit in every module.
2. A root for web based services - this adds the spring boot web starter which is incompatible with spring cloud and also shouldn't be inherited by shared libs.
3. A root for spring-cloud based services
- [ARTS-616] Refactor POMs 
[ARTS-616]: https://ndph-arts.atlassian.net/browse/ARTS-616
> [ARTS-616] Refactor POMs

- config-server/Dockerfile
- discovery-server/Dockerfile
- fhir-client/pom.xml
- fhir-client/src/main/java/uk/ac/ox/ndph/mts/fhir_client/FhirContextWrapper.java
- fhir-client/src/main/java/uk/ac/ox/ndph/mts/fhir_client/FhirServerResponseException.java
- fhir-client/src/main/java/uk/ac/ox/ndph/mts/fhir_client/Messages.java
- fhir-client/src/main/java/uk/ac/ox/ndph/mts/fhir_client/package-info.java
- init-service/Dockerfile
- pom.xml
- practitioner-service/Dockerfile
- role-service/Dockerfile
- sample-service/Dockerfile
- site-service/Dockerfile
Take the core functionality services use and package as a common module to share across the project.
The wrapper includes a few base generic functions that look like could fit all functionality currently implemented in site and practitioner services.
- [ARTS-599] common fhir client
[ARTS-599]: https://ndph-arts.atlassian.net/browse/ARTS-599
> [ARTS-599] Common FHIR context/client

- site-service/src/main/resources/site-configuration2.json
- site-service/src/main/resources/site-configuration3.json
- site-service/src/main/resources/site-configuration4.json
- site-service/src/main/resources/site-configuration5.json
- site-service/src/main/resources/site-configuration6.json
This PR has got Different Type Of Site Configs for creating New Trial Site API
- [ARTS-182] - create New Trial Site API 
[ARTS-182]: https://ndph-arts.atlassian.net/browse/ARTS-182
> [ARTS-631] Added Different Type Of Site Configs

- site-service/src/main/java/uk/ac/ox/ndph/mts/site_service/validation/SiteValidation.java
- site-service/src/main/resources/application.properties
- site-service/src/main/resources/site-configuration1.json
- site-service/src/main/resources/site-configuration2.json
- site-service/src/main/resources/site-configuration3.json
- site-service/src/main/resources/site-configuration4.json
- site-service/src/main/resources/site-configuration5.json
- site-service/src/main/resources/site-configuration6.json
- site-service/src/test/java/uk/ac/ox/ndph/mts/site_service/validation/SiteValidationTests.java
Validate Mandatory Fields Min and Max Length
- [ARTS-581] - Validate that the mandatory Fields exist and they don't exceed specified maximum length
[ARTS-581]: https://ndph-arts.atlassian.net/browse/ARTS-581
> [ARTS-581] Validate Mandatory Fields Min and Max Length

- role-service/src/test/java/uk/ac/ox/ndph/mts/role_service/controller/PermissionControllerTest.java
- sample-service/src/main/java/uk/ac/ox/ndph/mts/sample_service/security/authorisation/AuthorisationMethodSecurityMetadataSource.java
No ARTS issue number for this. Just keeping on top of the unchecked compiler warnings for raw types.
> Fixing unchecked compiler warnings

- docker-compose.yml
- gateway-server/src/main/resources/bootstrap-local.yml
- gateway-server/src/main/resources/bootstrap.yml
Updating the gateway routing to
http://gatewayurl:port/api/service
e.g.
http://localhost:8080/api/practitioner
- [ARTS-330] - added custom routing.
[ARTS-330]: https://ndph-arts.atlassian.net/browse/ARTS-330
> [ARTS-330] Custom gateway routing

- .github/workflows/docker-build-push.yml
Add a new job in the github workflow to check that the matrix finished in success. This makes it easier to add just 1 check on the main branch instead of multiple ones for each of the matrix entries.
- [ARTS-702]
[ARTS-702]: https://ndph-arts.atlassian.net/browse/ARTS-702
> [ARTS-702] Add a validation job for all matrix ones

- .github/workflows/docker-build-push.yml
- api-tests/common/utils.js
- api-tests/config/token-request.json
- api-tests/specs/practitioner-service/createperson.js
> Create practitioner with auth tests fixes

- build-tools/src/main/java/uk/ac/ox/ndph/mts/json_schema_generator/model/TrialConfigFile.java
Remove Id and rootUser properties from the json schema model.
> [FIX] Update Json Schema model

- security/src/main/java/uk/ac/ox/ndph/mts/security/authentication/AADWebSecurityConfig.java
Fix session management to stateless
- [ARTS-48] - Fix session management to stateless
[ARTS-48]: https://ndph-arts.atlassian.net/browse/ARTS-48
> [ARTS-48] - Set session to stateless

- docker-compose.yml
changing the docker compose to point to ci-trial
> changing the docker compose to point to ci-trial

- .github/workflows/docker-build-push.yml
- Dockerfile
- applicationinsights.json
- docker-compose.yml
Include the version (image tag and maven project version) in data sent to application insights.
- [ARTS-364] 
[ARTS-364]: https://ndph-arts.atlassian.net/browse/ARTS-364
> [ARTS-364] Include version in AppInsights data

- .github/workflows/docker-build-push.yml
- docker-compose.yml
- role-service-client/pom.xml
- security/pom.xml
Docker-compose logs can be useful to solve problems in the pre api-tests phase when the whole system is coming online.
** added a small fix on the POMs
> Upload docker-compose log as action artifact

- .github/workflows/docker-build-push.yml
- api-tests/common/utils.js
- api-tests/data/assign-roles/assign-roles.js
- api-tests/package.json
- api-tests/specs/assign-roles/assign-roles.js
- docker-compose.yml
The PR has files updated in order to handle the authorisation of assign roles and also the new permission 'assign-role'. The rest of the scenarios covering acceptance criteria will be merged into main as part of a different PR.
- [ARTS-621] - assign role permissions
[ARTS-621]: https://ndph-arts.atlassian.net/browse/ARTS-621
> [ARTS-621] - Assign Roles integration tests update

- role-service/src/main/java/uk/ac/ox/ndph/mts/role_service/Application.java
- role-service/src/main/java/uk/ac/ox/ndph/mts/role_service/RoleServiceApplication.java
adding trace when role service is loading to investigate issues when calling from init-service
- [ARTS-#] - some description
- [x ] I have included a short-meaningful title, description and changes for this PR
> fix - adding trace when role service is loading

- .github/workflows/docker-build-push.yml
Please replace this text with a summary of the change and which issue is fixed.
- [ARTS-#] - some description
> Move deployment trigger outside matrix job

- .github/workflows/docker-build-push.yml
Correct deployment repo url
Run deploy step after tests
- [ARTS-382] - tweak step order, correct repo name
[ARTS-382]: https://ndph-arts.atlassian.net/browse/ARTS-382
> [ARTS-382] deploy after tests, correct repo url

- api-tests/specs/createTrialSite/createNewTrialSite.js
As the tag only was running only the site services api tests skipping the others, I have removed it.
- [ARTS-764] - Deleted the only tag around site services api tests
[ARTS-764]: https://ndph-arts.atlassian.net/browse/ARTS-764
> [ARTS-764] - Updated the api tests

- docker-compose.yml
> [ARTS-729] Point back to main config

- api-tests/specs/role-service/permissions.js
- api-tests/specs/role-service/roleservice.js
The PR has code refactored to cover the authorisation of roles and permissions. The existing api tests have been updated accordingly.
Around 2 scenarios have been added to cover the acceptance criteria of arts-764.
- [ARTS-764] - roles and permissions
[ARTS-764]: https://ndph-arts.atlassian.net/browse/ARTS-764
> [ARTS-764] - Scenarios covering roles and permissions endpoint

- api-tests/specs/createTrialSite/createSitePermissions.js
This PR has got scenarios covered for viewing trial sites Automation Test
- [ARTS-76] - view trial sites api tests
[ARTS-76]: https://ndph-arts.atlassian.net/browse/ARTS-76
> [ARTS-76]view trial sites api tests

- role-service/src/main/resources/application-local.yml
- role-service/src/main/resources/bootstrap-local.yml
Local config to enable a developer to run role-service locally without a config server or dependency on the mts-trial-deployment-config repo
> fix/[ARTS-910] Role service local config

- api-tests/data/createTrialSite/siteExtensions.js
- api-tests/specs/createTrialSite/siteExtensions.js
The PR has tests written covering the custom string attribute feature
- [ARTS-172] - Custom String attribute
[ARTS-172]: https://ndph-arts.atlassian.net/browse/ARTS-172
> [ARTS-172] - API tests around custom string attribute

- .github/workflows/docker-build-push.yml
Disable the nightly workflow until CI fixed.
> Disable scheduled workflow
