NDPH-ARTS/mts-services

practitioner-service/README.md

Not a specific ARTS story. Just a text cleanup in README.md to suppress IntelliJ's various warnings.

Minor corrections with the practitioner service README.md file, to keep IntelliJ happy

---

api-tests/data/practitioner-service/createperson.js
api-tests/specs/practitioner-service/createperson.js

The pr has changes made to the practitioner services api tests. I have updated the following
1. The response status is asserted using the status error message along with the code.
2. The way the data is pulled from the .js file.
**Note:** No jira ticket is created for this one

Refactor Practitioner Service API tests

---

practitioner-service/pom.xml

Removed the azure.version from the practitioner-service, for a few reasons:
1. practitioner-service doesn't appear to use this variable
2. it already inherits azure.version from the parent POM
3. we probably don't want to accidentally end up overriding the parent POM's azure.version - I'm guessing we always want them to be the same. Declaring it in a couple of places increases risk of the values deviating.
There is no linked ARTS story for this.
As this is Azure-related, I'm not certain how to test if this has broken something or not. It successfully builds under Maven (i.e. the tests pass) and "docker-compose up" still gets the system up & running locally.

Removed the azure.version from the practitioner-service

---

.github/workflows/docker-build-push.yml
.github/workflows/realease-images-from-main.yml

We need a fixed label to allow repeatable and automatic deployment into fixed environments (like integration, qa, etc.).
- [ARTS-469] - publish the pre-built image from the build action when main branch is updated (after the PR is merged; "latest" tag) and every night ("nightly" tag).
[ARTS-469]: https://ndph-arts.atlassian.net/browse/ARTS-469

Publish named images from main branch

---

practitioner-service/src/main/java/uk/ac/ox/ndph/mts/practitioner_service/configuration/Configurations.java
practitioner-service/src/main/java/uk/ac/ox/ndph/mts/practitioner_service/controller/PractitionerController.java
practitioner-service/src/main/java/uk/ac/ox/ndph/mts/practitioner_service/converter/RoleAssignmentConverter.java
practitioner-service/src/main/java/uk/ac/ox/ndph/mts/practitioner_service/model/RoleAssignment.java
practitioner-service/src/main/java/uk/ac/ox/ndph/mts/practitioner_service/repository/FhirContextWrapper.java
practitioner-service/src/main/java/uk/ac/ox/ndph/mts/practitioner_service/repository/FhirRepo.java
practitioner-service/src/main/java/uk/ac/ox/ndph/mts/practitioner_service/repository/FhirRepository.java
practitioner-service/src/main/java/uk/ac/ox/ndph/mts/practitioner_service/repository/HapiFhirRepository.java
practitioner-service/src/main/java/uk/ac/ox/ndph/mts/practitioner_service/repository/RoleAssignmentStore.java
practitioner-service/src/main/java/uk/ac/ox/ndph/mts/practitioner_service/service/EntityService.java
practitioner-service/src/main/java/uk/ac/ox/ndph/mts/practitioner_service/service/PractitionerService.java
practitioner-service/src/main/java/uk/ac/ox/ndph/mts/practitioner_service/validation/PractitionerValidation.java
practitioner-service/src/main/java/uk/ac/ox/ndph/mts/practitioner_service/validation/RoleAssignmentValidation.java
practitioner-service/src/main/java/uk/ac/ox/ndph/mts/practitioner_service/validation/Validations.java
practitioner-service/src/test/java/uk/ac/ox/ndph/mts/practitioner_service/PractitionerServiceIntegrationTests.java
practitioner-service/src/test/java/uk/ac/ox/ndph/mts/practitioner_service/controller/PractitionerControllerTests.java
practitioner-service/src/test/java/uk/ac/ox/ndph/mts/practitioner_service/repository/HapiFhirRepositoryTests.java
practitioner-service/src/test/java/uk/ac/ox/ndph/mts/practitioner_service/service/PractitionerServiceTests.java
practitioner-service/src/test/java/uk/ac/ox/ndph/mts/practitioner_service/validation/RoleAssignmentValidationTests.java

This is the first PR to support the functionality of assigning roles to users. In a second PR we'll add extended validation to make sure the referenced entities (practitioner, role, site) are indeed exist.
- [ARTS-465] - A basic implementation for assigning roles.
[ARTS-465]: https://ndph-arts.atlassian.net/browse/ARTS-465

[ARTS-465] A basic implementation for assigning roles to users

---

api-tests/README.md
api-tests/data/common/utils.js
api-tests/data/role-service/permissions.js
api-tests/data/role-service/roleservice.js
api-tests/specs/role-service/permissions.js

1. The PR has automation tests written around settings Permissions for a role. The tests check for a valid and negative responses.
2. I have moved the function 'getRandomString' to a utils folder to use globally. 
3. Updated the readme as per the changes done to permissions.
4. Only one acceptance criteria of the story 101 has been added to automation tests, the other one which is tested via a json file configuration (arts-350) hasn't been added to automation as its not possible and also not needed to be tested separately as part of regression. Test ticker, https://ndph-arts.atlassian.net/browse/ARTS-559
- [ARTS-101] - Set permissions for a role
- [ARTS-580] - Covers the test approach.
- 
- [Yes ] Branch name follows convention (feature/arts-###-short-name OR fix/arts-###-short-name)
- …

[ARTS-101] Permissions automation api tests

---

practitioner-service/src/main/java/uk/ac/ox/ndph/mts/practitioner_service/configuration/PractitionerConfigurationProvider.java
practitioner-service/src/main/java/uk/ac/ox/ndph/mts/practitioner_service/model/PractitionerAttributeConfiguration.java
practitioner-service/src/main/java/uk/ac/ox/ndph/mts/practitioner_service/model/PractitionerConfiguration.java

- Refactoring of fetching the practitioner configuration file from spring config with spring annotation instead with an http request.
- What allowed us to make the refactor is changing the configuration file from json to yml, essentially making it a property file, which is supported natively by spring cloud config) . [Will be updated in the second repo. ](https://github.com/NDPH-ARTS/mts-trial-deployment-config/pull/35)
- [ARTS-562] - Refactor practitioner service configuration fetching
[ARTS-562]: https://ndph-arts.atlassian.net/browse/ARTS-562

[ARTS-562] Initialize practitioner service configuration with Spring

---

.github/workflows/docker-build-push.yml
config-server/Dockerfile
init-service/Dockerfile
practitioner-service/Dockerfile
role-service/Dockerfile
sample-service/Dockerfile
site-service/Dockerfile
trial-config-service/Dockerfile

Docker builds take a long time since **every** container downloads its own maven dependencies on **every** build. This PR add a step in the docker files to enable the dependencies to be cached as a separate layer and be reused between build actions on the same machine.
- [ARTS-589] cache maven deps as docker layer
[ARTS-589]: https://ndph-arts.atlassian.net/browse/ARTS-589

[ARTS-589] Add a docker step to enable caching maven dependencies as a layer

---

site-service/README.md
site-service/pom.xml
site-service/src/main/java/uk/ac/ox/ndph/mts/site_service/configuration/WebConfig.java
site-service/src/main/java/uk/ac/ox/ndph/mts/site_service/controller/SiteController.java
site-service/src/main/java/uk/ac/ox/ndph/mts/site_service/converter/OrganizationConverter.java
site-service/src/main/java/uk/ac/ox/ndph/mts/site_service/converter/SiteConverter.java
site-service/src/main/java/uk/ac/ox/ndph/mts/site_service/exception/InvariantException.java
site-service/src/main/java/uk/ac/ox/ndph/mts/site_service/model/Site.java
site-service/src/main/java/uk/ac/ox/ndph/mts/site_service/repository/EntityStore.java
site-service/src/main/java/uk/ac/ox/ndph/mts/site_service/repository/FhirContextWrapper.java
site-service/src/main/java/uk/ac/ox/ndph/mts/site_service/repository/FhirRepo.java
site-service/src/main/java/uk/ac/ox/ndph/mts/site_service/repository/FhirRepository.java
site-service/src/main/java/uk/ac/ox/ndph/mts/site_service/repository/HapiFhirRepository.java
site-service/src/main/java/uk/ac/ox/ndph/mts/site_service/repository/SiteStore.java
site-service/src/main/java/uk/ac/ox/ndph/mts/site_service/service/Services.java
site-service/src/main/java/uk/ac/ox/ndph/mts/site_service/service/SiteService.java
site-service/src/main/java/uk/ac/ox/ndph/mts/site_service/service/SiteServiceImpl.java
site-service/src/test/java/uk/ac/ox/ndph/mts/site_service/SiteServiceImplIntegrationTests.java
site-service/src/test/java/uk/ac/ox/ndph/mts/site_service/controller/SiteControllerTests.java
site-service/src/test/java/uk/ac/ox/ndph/mts/site_service/converter/SiteConverterTest.java
site-service/src/test/java/uk/ac/ox/ndph/mts/site_service/repository/HapiFhirRepositoryTests.java
site-service/src/test/java/uk/ac/ox/ndph/mts/site_service/service/SiteServiceImplTests.java
site-service/src/test/java/uk/ac/ox/ndph/mts/site_service/validation/SiteValidationTests.java

* Added get-all-sites endpoint to site-service `GET ${site-service}/sites`
* Added new endpoint (translating from the FHIR API), matching tests, updated README to document API.
* Site model now has site ID (the FHIR ID), required for matching parentSiteId
- [ARTS-404] - get sites from site service
[ARTS-404]: https://ndph-arts.atlassian.net/browse/ARTS-404

[ARTS-404] Get sites from site service

---

role-service/src/main/java/uk/ac/ox/ndph/mts/role_service/controller/RoleController.java
role-service/src/test/java/uk/ac/ox/ndph/mts/role_service/controller/RoleControllerTest.java

This sub-task enables a performance improvement in the authorisation component ARTS-361 at the point it looks up roles for the user.   See Alex's review of PR  https://github.com/NDPH-ARTS/mts-services/pull/111#discussion_r572121101  
#111
- [ARTS-610] Create new api endpoint in role service to get roles by list of ids
- [ARTS-361] Validate user permissions in authorisation
[ARTS-610]: https://ndph-arts.atlassian.net/browse/ARTS-610
[ARTS-361]: https://ndph-arts.atlassian.net/browse/ARTS-361

[ARTS-610] New GET endpoint in role-service to return multiple roles by ID

---

.dockerignore

Add a dockerignore file to remove items from the docker build context that typically exist locally but aren't needed.
- [ARTS-623] Add dockerignore file
[ARTS-623]: https://ndph-arts.atlassian.net/browse/ARTS-623

[ARTS-623] Add dockerignore file

---

docker-compose.yml
init-service/src/main/java/uk/ac/ox/ndph/mts/init_service/model/Site.java
init-service/src/main/java/uk/ac/ox/ndph/mts/init_service/service/ServiceInvoker.java
init-service/src/main/java/uk/ac/ox/ndph/mts/init_service/service/TrialService.java
init-service/src/main/resources/application.properties
init-service/src/test/java/uk/ac/ox/ndph/mts/init_service/service/SiteServiceTest.java

* Update API client to site-service
* Added extra logging in init-service to make diagnosing problems easier
* Added updates to get correct configuration file in local & local-docker environments
- [ARTS-627] - init-service failing - this PR fixes the interface to the site-service - other random fails seen
[ARTS-627]: https://ndph-arts.atlassian.net/browse/ARTS-627

[ARTS-627] make init-service use correct site-service API

---

.ci/docker/check-docker-compose-services.sh
.gitattributes
.github/workflows/docker-build-push.yml
config-server/Dockerfile
discovery-server/Dockerfile
docker-compose.yml
init-service/Dockerfile
init-service/src/main/resources/application.properties
practitioner-service/Dockerfile
role-service/Dockerfile
sample-service/Dockerfile
site-service/Dockerfile

Make some changed to lower the requirements of running the system via docker-compose, plus some other small fixes
- Use a single SQL server in docker-compose
- Move containers to a smaller java base image
- Maven config to retry on download failure
- Use docker buildkit in CI builds
- Run init-service in ci integration test

Smaller docker-compose footprint

---

.github/workflows/docker-build-push.yml
docker-compose.yml

Add azure credentials when running Api Tests
- [ARTS-353] - Add azure credentials when running Api Tests. Those credentials will be used by the init-service to retrieve the token and being able to access other services with it.
[ARTS-353]: https://ndph-arts.atlassian.net/browse/ARTS-353

[ARTS-353] add azure credentials to api tests

---

.ci/docker/check-docker-compose-services.sh
.github/workflows/docker-build-push.yml
docker-compose.yml
init-service/src/main/java/uk/ac/ox/ndph/mts/init_service/config/AzureTokenService.java
practitioner-service/src/main/resources/application-local.yml
practitioner-service/src/test/resources/application.yml
sample-service/src/main/resources/application-local.properties
sample-service/src/test/resources/application.yml
security/src/main/java/uk/ac/ox/ndph/mts/security/authorisation/AuthorisationService.java
security/src/main/resources/application.yml

Workaround to allow init service to authenticate to the system by using username/password and a new "scope". The actual code changed are small, but we pass different environment variables that make the azure identity library act differently.

[ARTS-353] Workaround for init authentication

---

.github/workflows/docker-build-push.yml
api-tests/common/utils.js
api-tests/package-lock.json
api-tests/package.json
api-tests/specs/createTrialSite/createNewTrialSite.js
api-tests/specs/practitioner-service/createperson.js
api-tests/specs/role-service/permissions.js
api-tests/specs/role-service/roleservice.js
api-tests/specs/zassign-roles/assign-roles.js

Code added to fetch token id of a user from azure active directory. The token id is the bearer header used to authorise in creating a person via practitioner services.
The related api tests for create person is updated with the code that fetches the token Id.
I have added a function to the utils file which can be used globally.
The token id parameters are encoded in a json file that are configurable.
- ARTS-609 - Create person authorisation
- ARTS-654 - Fetch Token Id from azure active directory

[ARTS-609] - Create person API tests to handle authorisation

---

Dockerfile
applicationinsights.json
practitioner-service/src/main/resources/bootstrap.yml
role-service/src/main/resources/bootstrap.yml
site-service/src/main/resources/bootstrap.yml

This adds application insights to all services to collect logs and metrics.
This can be merged without waiting for the deployment related PR.
- [ARTS-364] Collect logs/metrics
- Add spring cloud config "fail-fast" because if the config isn't available at startup, no point to bring up the/any service.
[ARTS-364]: https://ndph-arts.atlassian.net/browse/ARTS-364

[ARTS-364] Add Application Insights for logs and metrics

---

docker-compose.yml

Fix of typo in env var name in docker compose.

[Fix] Typo in docker compose

---

.ci/docker/check-docker-compose-services.sh
.github/workflows/docker-build-push.yml
Dockerfile

Optimize the docker builds to reduce time.
- Checks if the runtime image already exists with the right tag before building it.
- Reuse the maven dependencies across services and builds if it hasn't change (cached as a layer)
- Start using a slim base for the runtime image (~100MB less)
- Stop waiting for the business services in the CI since that better represent a real startup of the system on the cloud (init is able to retry if the service isn't online yet).

Optimize docker build

---

site-service/src/main/java/uk/ac/ox/ndph/mts/site_service/repository/FhirContextWrapper.java
site-service/src/main/resources/application-local.yml

Increasing result set size form FHIR to 50
We are currently only returning a max of 10 results from FHIR. Increasing result set size form FHIR to 50.
This change is linked to the config repo changes and therefore API tests will fail until the linked PR is merged into main - https://github.com/NDPH-ARTS/mts-trial-deployment-config/pull/87/files
- [ARTS-793] - Increasing result set size form FHIR to 50
[ARTS-793]: https://ndph-arts.atlassian.net/browse/ARTS-793

[ARTS-793] - Increasing default search result set from FHIR

---

api-tests/data/assign-roles/assign-roles.js
api-tests/data/createTrialSite/createNewTrialSite.js
api-tests/data/createTrialSite/sitesaddress.js
api-tests/data/practitioner-service/createperson.js
api-tests/data/role-service/permissions.js
api-tests/data/role-service/roleservice.js
api-tests/specs/createTrialSite/createNewTrialSite.js
api-tests/specs/createTrialSite/sitesaddress.js
api-tests/specs/practitioner-service/createperson.js
api-tests/specs/profile/profile.js
api-tests/specs/role-service/permissions.js
api-tests/specs/role-service/roleservice.js
api-tests/specs/zassign-roles/assign-roles.js

The PR contains a set of scenarios to check the presence of an address at CCO and LCC level. Negative scenarios added to see if the address field present for non-configured sites like regions and countries fails.
- [ARTS-207] - Address field added to the site with no validation
[ARTS-207]: https://ndph-arts.atlassian.net/browse/ARTS-207

[ARTS-207] - API tests added to check the address entity at sites endpoint

---

role-service/src/main/resources/db/changelog/changelog-permission-data.xml

Missing permissions in the db are added for the CI to be green again.

[FIX] Add missing permissions to allow ci to be green

---

.github/workflows/docker-build-push.yml
config-server/src/main/resources/application.yml
discovery-server/src/main/resources/application.yml
docker-compose.yml
init-service/pom.xml
init-service/src/main/resources/bootstrap.yml
pom.springcloud.xml
sample-service/src/main/resources/application-local.properties
sample-service/src/main/resources/application-local.yml

Improve the overall stability of the docker-compose based system.
- [ARTS-827] - Update spring cloud services to also use actuator and docker-compose to use its liveness probe for health checks.
- Align restart policy on docker-compose
- Add retry for config on the init-service (probably should be replicated to the others as well)
[ARTS-827]: https://ndph-arts.atlassian.net/browse/ARTS-827

[ARTS-827] Improve stability and health checks on docker-compose

---

api-tests/data/createTrialSite/createNewTrialSite.js
api-tests/data/createTrialSite/createSitePermission.js
api-tests/specs/createTrialSite/createNewTrialSite.js
api-tests/specs/createTrialSite/createSitePermissions.js

Automated API tests for create-site with auth feature
- [ARTS-622] - Automated API tests
[ARTS-622]: https://ndph-arts.atlassian.net/browse/ARTS-622

[ARTS-622] - API tests covering create site auth feature

---

security/src/main/java/uk/ac/ox/ndph/mts/security/authentication/AADWebSecurityConfig.java

Health checks endpoints should allow access without any authNZ

[fix] Allow access /actuator/health without any auth

---

.github/workflows/docker-build-push.yml

Run nightly deploy after build not test
- [ARTS-382] - some description
[ARTS-382]: https://ndph-arts.atlassian.net/browse/ARTS-382

[ARTS-382] Depend on build not test for nightly deploy

---

role-service/src/main/resources/application.properties

Remove an obsolete properties file from the role-service, which anyway isn't taking affect since the exact same properties are coming from the config-server and cannot be overridden (be default)

[fix] Remove obsolete properties file

---

init-service/src/main/java/uk/ac/ox/ndph/mts/init_service/loader/Loader.java
init-service/src/main/java/uk/ac/ox/ndph/mts/init_service/loader/LoaderProgress.java
init-service/src/test/java/uk/ac/ox/ndph/mts/init_service/loader/LoaderTest.java

Init service starts only when ALL expected services are registered.
In this way we improve the init service to succeed and not reach any undesired state due to partial initialization.
It can still happen (e.g. service is unregistered after the check was done), but it improves the chance of success.
Discovery client was added to the init-service. We query it for the registered services and we block the init until we verify all are registered.

Init service starts only when ALL expected services are registered

---

init-service/src/main/java/uk/ac/ox/ndph/mts/init_service/model/Practitioner.java
init-service/src/main/java/uk/ac/ox/ndph/mts/init_service/model/Site.java
init-service/src/main/java/uk/ac/ox/ndph/mts/init_service/model/Trial.java
practitioner-service/src/main/java/uk/ac/ox/ndph/mts/practitioner_service/model/PractitionerAttributeConfiguration.java
practitioner-service/src/main/java/uk/ac/ox/ndph/mts/practitioner_service/model/PractitionerConfiguration.java
practitioner-service/src/test/java/uk/ac/ox/ndph/mts/practitioner_service/controller/PractitionerControllerTests.java
site-service/src/main/java/uk/ac/ox/ndph/mts/site_service/model/AddressConfiguration.java
site-service/src/main/java/uk/ac/ox/ndph/mts/site_service/model/SiteAttributeConfiguration.java
site-service/src/main/java/uk/ac/ox/ndph/mts/site_service/model/SiteConfiguration.java
site-service/src/test/java/uk/ac/ox/ndph/mts/site_service/SiteServiceImplIntegrationTests.java
site-service/src/test/java/uk/ac/ox/ndph/mts/site_service/TestSiteConfiguration.java
site-service/src/test/java/uk/ac/ox/ndph/mts/site_service/controller/SiteControllerTests.java

This PR adds validation on the java classes themselves and results in detailed errors on load time if the fetched config doesn't fit the classes (rather than just dependency injection errors like before).
- [ARTS-884] - Config classes validation
[ARTS-884]: https://ndph-arts.atlassian.net/browse/ARTS-884

[ARTS-884] Validate configuration classes

---

api-tests/specs/assign-roles/assign-roles.js
api-tests/specs/createTrialSite/createNewTrialSite.js
api-tests/specs/createTrialSite/createSitePermissions.js
api-tests/specs/createTrialSite/sitesaddress.js

PR contains api tests written around role assignment uri. The scenarios check 
- if the user with an identical token id gets a successful response and 
- if the user with a non-identical token id gets an access denied response
- [ARTS-764] - get my roles auth
- [ARTS-885] - Test Scenarios
[ARTS-764]: https://ndph-arts.atlassian.net/browse/ARTS-764
[ARTS-885]: https://ndph-arts.atlassian.net/browse/ARTS-885

[ARTS-764] - API tests on Role Assignment URI

---

config-server/src/main/resources/bootstrap-local.yml
docker-compose.yml
init-service/src/main/resources/bootstrap-local.yml
practitioner-service/src/main/resources/bootstrap-local.yml
role-service/src/main/resources/bootstrap-local.yml
security/src/main/resources/application.yml
site-service/src/main/resources/bootstrap-local.yml

Init-service waits for other services to appear in the discovery-server registry (See https://github.com/NDPH-ARTS/mts-services/blob/main/init-service/src/main/java/uk/ac/ox/ndph/mts/init_service/loader/Loader.java).   At the moment all services have discovery switched off in local profile.   So if we we want the option to run init-service locally, we need to run discovery locally, or do a workaround.
- [ARTS-916] 
[ARTS-196]: https://ndph-arts.atlassian.net/browse/ARTS-196
[ARTS-916]: https://ndph-arts.atlassian.net/browse/ARTS-916

[ARTS 916] fix config for local discovery server 
